NAME: TreeCrownGraph
MODEL:
  NAME: Graph # YOLO, DETECTREE2, MASKRCNN
  LEARNING_RATE: 0.0001
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  EPOCHS: 100
  BATCH_SIZE: 16
  IMAGE_SIZE: 640
  WORKERS: 8
  PROJECT: runs/train
  NAME: TreeCrownGraph
  EXIST_OK: True
  PRETRAINED: True
  OPTIMIZER: Adam
  DETERMINISTIC: True
  SEED: 42
  LR0: 0.0001
  MASKRCNN_BACKBONE: 'resnet101' # resnet101, resnet50, Swin-L, Swin-B, Swin-T
 